Add context (res id and name) when downloading data
Public-Health-Scotland/phsopendata pull request #24
Opened 2024-03-28 09:40 UTC by Moohan

This code works but is just a draft idea.

The problem was highlighted in [this teams chat](https://teams.microsoft.com/l/message/19:9620ef6cf8234d50a0f95caba65a3edf@thread.tacv2/1711384080545?tenantId=10efe0bd-a030-4bca-809c-b5e6745e499a&groupId=ec4250f9-b70a-4f32-9372-a232ccb4f713&parentMessageId=1711384080545&teamName=PHS%20Data%20and%20Intelligence%20Forum&channelName=Posit%20Technical%20Queries&createdTime=1711384080545), when using `get_dataset` if the dataset doesn't include a variable like `date` it becomes impossible to tell which rows are from which resource as `get_dataset` just joins them into a single tibble.

I can think of a few solutions:

1. Add `res_id` and/or `resource_name` to the data by default (what this PR currently does).
2. Optionally add them with a new argument e.g. `add_context = TRUE` this could be:
    1. TRUE by default
    2. FALSE by default
3. Do any of the above at the 'resource level' i.e. this PR currently only does this to `get_dataset` but I could move the code 'down' to `get_resource` to add the 'context' there, similarly we could pass through any `add_context` parameter...

2024-03-28 10:53 UTC, csillasch commented
This is great! I`m probably leaning toward having it optional (but perhaps default to TRUE for get_dataset) and I think it might be worth having the option for get_resource as well (but would perhaps default to FALSE for get_resource)?

2024-04-11 12:17 UTC, Moohan commented
From discussion

- [ ] Add some more tests with other datasets and resources (d3eaaf84-0f3b-4fb8-9460-e33503095fbe).
- [ ] Should missing modified date be created date.
- [ ]

2024-04-19 14:28 UTC, Moohan commented
@csillasch and @ross-hull I think this is done now.

The modified date still returns as NA if nothing is returned from the API (we discussed possibly setting it to the created date but don't remember the final decision?

We talked about adding some additional tests, I've added some but please let me know if you want anything else specifically testing - or importantly if you find a resource / dataset this isn't working for in which case I'll definitely add that and fix whatever the issue is!

2024-04-23 09:40 UTC, ross-hull commented
This looks good to me. And using it as a user was simple. One thing that I wondered is if it is worth having the same naming convention between the new context columns, as is already used in the open data? The context columns are snake case while the others are upper camel.

2024-04-24 11:17 UTC, csillasch requested changes
Looks good! 

I spotted unexpected behaviour when testing on the General Practitioner Contact Details dataset: modified date is returned correctly using get_dataset but returns NULL with get_resource("647b256e-4a03-4963-8402-bf559c9e2fff")

Suggested a change to sort this which works for the resource but might be worth testing against some of the others - especially where it worked fine previously.

2024-04-24 13:21 UTC, Moohan commented
> This looks good to me. And using it as a user was simple. One thing that I wondered is if it is worth having the same naming convention between the new context columns, as is already used in the open data? The context columns are snake case while the others are upper camel.

Fair enough, do these names look good?
```
"ResId" (or "ResID"?)
"ResName"
"ResCreatedDate"
"ResModifiedDate"
```

2024-04-24 14:06 UTC, Moohan commented on R/get_resource.R
> +    res_modified_date <- context_content$result$modified
I started writing a test for this (your suggestion does seem to fix) but I noticed another issue where the date type changes when binding together the dataset.

https://github.com/r-lib/vctrs/issues/1930

2024-04-24 15:57 UTC, csillasch reviewed
Get_dataset seems to handle it fine but get_resource is returning the dates as lists - all your changes look OK to me so not sure how/why this is happening

2024-05-09 11:27 UTC, csillasch approved these changes

2024-06-13 12:08 UTC, merged